issue/48 Add documentation for migrating to rub from adapt-cli
cgkineo/rub-cli pull request #49
Opened 2022-05-05 14:12 UTC by swashbuck

Resolves #48

2022-05-10 08:20 UTC, oliverfoster requested changes

2022-05-10 08:20 UTC, oliverfoster commented on README.md
> +4. Finally, delete the `course` folder that lives in `src`. Otherwise, the `build` folder will be recreated each time you run rub.
```suggestion
2. Create a folder inside the `builds` folder using your module name (e.g. `p101)
3. Move/remove the `src/course` folder into the `builds/p101` folder 
4. Run `rub dev p101` to build
```

2022-05-10 16:17 UTC, oliverfoster commented on README.md
> +3. Move/remove the `src/course` folder into the `builds/p101` folder
Yup, that works.

2022-05-10 16:28 UTC, oliverfoster commented on README.md
> +3. Move/remove the `src/course` folder into the `builds/p101` folder
CLean up as you wish, my comment was more about removing `grunt` from the entire process.

2022-05-11 22:10 UTC, swashbuck commented
@oliverfoster I've revised the text a bit.  Let me know if this is approved and can be merged.

2022-05-12 08:20 UTC, oliverfoster commented on README.md
> +3. Move the contents of the 'src/course' folder into 'builds/p101'. Then, remove 'src/course' entirely.
```suggestion
3. Move the contents of the 'src/course' folder into 'builds/p101/course'. Then, remove 'src/course' entirely.
```

2022-05-12 14:18 UTC, oliverfoster approved these changes

2022-05-12 14:19 UTC, merged