fixes issue/57
cgkineo/rub-cli pull request #62
Opened 2022-12-12 05:57 UTC by NayanKhedkar

2022-12-12 11:35 UTC, oliverfoster requested changes
Remove line end `;` semi colons
Remove unnecessary brackets from single argument fat-arrow  functions
Remote unnecessary fat arrow functions

2022-12-12 11:35 UTC, oliverfoster commented on commands/045zip.js
> +      });
```suggestion
      output.on('close', resolve)
```

2022-12-12 11:35 UTC, oliverfoster commented on commands/045zip.js
> +      });
```suggestion
      output.on('end', resolve)
```

2022-12-12 11:35 UTC, oliverfoster commented on commands/045zip.js
> +      });
```suggestion
      zipFiles.forEach(file => {
        archive.append(fs.createReadStream(file.path), { name: file.name })
      })

      archive.on('error', err => {
        log(err)
        resolve()
      })
```

2022-12-12 11:35 UTC, oliverfoster commented on commands/045zip.js
> +      });
```suggestion
      })
```

2022-12-12 11:35 UTC, oliverfoster commented on commands/046zipaat.js
> +      });
```suggestion
      })
```

2022-12-12 11:35 UTC, oliverfoster commented on commands/046zipaat.js
> +      });
```suggestion
      output.on('close', resolve)
```

2022-12-12 11:35 UTC, oliverfoster commented on commands/046zipaat.js
> +      });
```suggestion
      output.on('end', resolve)
```

2022-12-12 11:35 UTC, oliverfoster commented on commands/046zipaat.js
> +      });
```suggestion
      zipFiles.forEach(file => {
        archive.append(fs.createReadStream(file.path), { name: file.name })
      })
```

2022-12-12 11:35 UTC, oliverfoster commented on commands/046zipaat.js
> +      });
```suggestion
      archive.on('error', err => {
        log(err)
        resolve()
      })
```

2022-12-13 06:46 UTC, NayanKhedkar commented
implemented requested changes

2022-12-13 09:54 UTC, oliverfoster approved these changes

2022-12-13 09:55 UTC, merged